--- #YAML:1.0
name:               Algorithm-MasterMind
version:            v0.4.0
abstract:           Framework for algorithms that solve the MasterMind game
author:
    - JJ Merelo <jj@merelo.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Combinatorics:  0
    Algorithm::Evolutionary:  0.75
    Clone::Fast:          0
    Test::More:           0
    version:              0.77
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
