--- #YAML:1.0
name:                Algorithm-MasterMind
version:             0.0.1
abstract:            Framework for algorithms that solve the MasterMind game
license:             ~
author:              
    - JJ Merelo <jj@merelo.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Algorithm::Evolutionary:       0.71
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
